using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace abp.Tests
{
    public class Test : TestBase
    {
        //<suite-custom-code-autogenerated>
        protected Test()
        {

        }

        public Test(Guid id, int age, DateTime dOB, string? name = null)
            : base(id, age, dOB, name)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}