using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace abp.Tests
{
    public class TestManager : TestManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TestManager(ITestRepository testRepository)
            : base(testRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}