using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace abp.Templates
{
    public class TemplateManager : TemplateManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TemplateManager(ITemplateRepository templateRepository)
            : base(templateRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}