using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace abp.Templates
{
    public class Template : TemplateBase
    {
        //<suite-custom-code-autogenerated>
        protected Template()
        {

        }

        public Template(Guid id, int number, string? name = null, string? description = null)
            : base(id, number, name, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}