using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace abp.Feedbacks
{
    public class FeedbackManager : FeedbackManagerBase
    {
        //<suite-custom-code-autogenerated>
        public FeedbackManager(IFeedbackRepository feedbackRepository)
            : base(feedbackRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}