using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace abp.TestTemplates
{
    public class TestTemplateManager : TestTemplateManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TestTemplateManager(ITestTemplateRepository testTemplateRepository)
            : base(testTemplateRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}