apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: "{{ .Release.Name }}-{{ .Chart.Name }}"
        ports:
        - name: "http"
          containerPort: 80
        env:
        - name: "DOTNET_ENVIRONMENT"
          value: "{{ .Values.global.dotnetEnvironment }}"
        - name: "App__SelfUrl"
          value: "{{ include "abp.hosts.httpapi" . }}"
        - name: "App__AngularUrl"
          value: "{{ include "abp.hosts.angular" . }}"
        - name: "App__CorsOrigins"
          value: "https://*.abp.com,{{ include "abp.hosts.angular" . }}"                      
        - name: "App__RedirectAllowedUrls"
          value: "https://*.TestAppBlazorWasm.com,{{ include "abp.hosts.angular" . }}"                 
        - name: App__DisablePII
          value: "{{ .Values.global.disablePII }}"        
        - name: "ConnectionStrings__Default"
          value: "{{ .Values.global.connectionStrings.default | replace "[RELEASE_NAME]" .Release.Name }}"
        - name: "AuthServer__Authority"
          value: "{{ include "abp.hosts.httpapi" . }}"
        - name: "AuthServer__RequireHttpsMetadata"
          value: "false"
        - name: "StringEncryption__DefaultPassPhrase"
          value: "{{ .Values.global.stringEncryptionDefaultPassPhrase }}"
        - name: "AbpStudioClient__StudioUrl"
          value: "{{ .Values.global.abpStudioClient.studioUrl }}"
        - name: "AbpStudioClient__IsLinkEnabled"
          value: "{{ .Values.global.abpStudioClient.isLinkEnabled }}"